[global]
bind = "0.0.0.0"
port = 6722
feature = 'Penetrate'
log_level = "info"
handshake = {type = "Token", params = "my token"}
reuse_port = false
fast_reopen = false
# webhook = { type = "Telegram", params = { chat_id = "xxxx", bot_token = "xxxxx" } }

[penetrate]
features = []

[compress.lz4]
buffer = 10


